# Generated by Django 5.2.15 on 2026-06-28 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("raw_file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("row_count_raw", models.PositiveIntegerField(default=0)),
                ("row_count_clean", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_spend_inr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_spend_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("top_merchants", models.JSONField(default=list)),
                ("anomaly_count", models.PositiveIntegerField(default=0)),
                ("per_category_spend", models.JSONField(default=dict)),
                ("narrative", models.TextField(blank=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("llm_raw_response", models.JSONField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_id", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("merchant", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("account_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_anomaly", models.BooleanField(default=False)),
                ("anomaly_reason", models.TextField(blank=True)),
                ("llm_category", models.CharField(blank=True, max_length=50)),
                ("llm_raw_response", models.JSONField(blank=True, null=True)),
                ("llm_failed", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "account_id"],
                        name="jobs_transa_job_id_12cc1c_idx",
                    ),
                    models.Index(
                        fields=["job", "is_anomaly"],
                        name="jobs_transa_job_id_c59f80_idx",
                    ),
                ],
            },
        ),
    ]
